### ISSUE TITLE
Roadmap Sep - Dec 2018

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#631]
# Roadmap 2018
Since AE is a fairly large project, we should focus on things based on phases. These phases should remind us what we should focus on (and to be honest it prevents us to get lost in all these tasks).

So if you get lost, feel free to join the roadmap task force ;-)

### Phase 1 Sep/Oct (Cleanup and implement new concepts)
- [x] Serialise most packets in handler files
- [x] Rewrite all handler functions
- - [x] AreaTriggerHandler.cpp
- - [x] AuctionHandler.cpp
- - [x] BattlegroundHandler.cpp
- - [x] CalendarHandler.cpp
- - [x] ChannelHandler.cpp
- - [x] CharacterHandler.cpp
- - [x] ChatHandler.cpp
- - [x] CombatHandler.cpp
- - [x] DuelHandler.cpp
- - [x] GMTicketHandler.cpp
- - [x] GroupHandler.cpp
- - [x] GuildHandler.cpp
- - [x] ItemHandler.cpp
- - [x] LfgHandler.cpp
- - [x] LootHandler.cpp
- - [x] MailHandler.cpp
- - [x] MiscHandler.cpp
- - [x] MovementHandler.cpp
- - [x] NPCHandler.cpp
- - [x] PetHandler.cpp
- - [x] QueryHandler.cpp
- - [x] QuestHandler.cpp
- - [x] SocialHandler.cpp
- - [x] SpellHandler.cpp
- - [x] TaxiHandler.cpp
- - [x] TradeHandler.cpp
- - [x] VehicleHandler.cpp
- [x] Replace most update fields with structures (WoWXXX)

### Phase 2 Oct/Nov (Further rewrite of legacy base classes)
- [x] Rewrite more legacy functions for already split files.

### Phase 3 Nov/ Dec (Scripting)
~~- [ ] Replace simple legacy scripts with new methods (prevent "duplicate" code)~~ Out of scope
~~- [ ] LUAEngine documentation~~ Out of scope

**Comment by schnek** [comment]
1. scripts, create / rename tables to understand where to enter text. (create a list from all table_text).
2. do not create large files (again for understanding)
